# Generated by Django 4.2.3 on 2023-07-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phoneNo', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=254)),
                ('issue', models.TextField()),
            ],
        ),
    ]
